import { missionData } from "../data/missionData";

function MissionReportCenter({ selectedZone }) {
  const data = missionData[selectedZone];

  const exportReport = () => {
    const report = `
COSMIC PARADOX MISSION REPORT

ZONE: ${selectedZone}

THREAT LEVEL:
${data.threat}

CONFIDENCE:
${data.confidence}

STATUS:
${data.status}

AI RECOMMENDATION:
${data.recommendation}

Generated by:
COSMIC PARADOX AI CORE
`;

    const blob = new Blob(
      [report],
      { type: "text/plain" }
    );

    const url =
      window.URL.createObjectURL(blob);

    const link =
      document.createElement("a");

    link.href = url;

    link.download =
      `${selectedZone}_Mission_Report.txt`;

    link.click();

    window.URL.revokeObjectURL(url);
  };

  return (
    <div
      style={{
        background: "rgba(10,15,35,0.7)",
        border: "1px solid rgba(0,255,255,0.2)",
        borderRadius: "24px",
        padding: "25px",
        marginTop: "25px"
      }}
    >
      <h2
        style={{
          color: "#00ffff",
          marginBottom: "15px"
        }}
      >
        MISSION REPORT CENTER
      </h2>

      <button
        onClick={exportReport}
        style={{
          background:
            "linear-gradient(135deg,#00395f,#005f88)",
          color: "white",
          border: "none",
          padding: "14px 20px",
          borderRadius: "12px",
          cursor: "pointer",
          fontWeight: "bold"
        }}
      >
        EXPORT REPORT
      </button>
    </div>
  );
}

export default MissionReportCenter;